<a href="https://colab.research.google.com/github/shivamsinghtomar78/MathemticsForML/blob/main/matrics_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
p=np.array([[1,7],[2,1],[3,2]])
print(p)

[[1 7]
 [2 1]
 [3 2]]


In [14]:
q=np.array([[1,1],[1,-1],[1,0]])
print(q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [15]:
c1=np.add(p,q)
print(c1)

[[2 8]
 [3 0]
 [4 2]]


In [16]:
c1=np.subtract(p,q)
print(c1)

[[0 6]
 [1 2]
 [2 2]]


In [18]:
n=np.array([[1,2,3],[4,5,6]])
print(n)

[[1 2 3]
 [4 5 6]]


In [19]:
r=np.dot(p,n)
print(r)

[[29 37 45]
 [ 6  9 12]
 [11 16 21]]
