<a href="https://colab.research.google.com/github/shivamsinghtomar78/MathemticsForML/blob/main/vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
v=np.array([1,2,3])
w=np.array([0.1,0.2,0.3])

In [7]:
#addition
print(v+w)

[1.1 2.2 3.3]


In [5]:
#subtraction
print(v-w)

[0.9 1.8 2.7]


In [9]:
#vector multiplication
print(3*v)
print(5*w)

[3 6 9]
[0.5 1.  1.5]


In [10]:
#length
print(np.linalg.norm(v))
print(np.linalg.norm(w))

3.7416573867739413
0.37416573867739417


In [11]:
#dot product
s=np.dot(v,w)
print(s)

1.4


In [12]:
#cross product
print(np.cross(v,w))

[-1.11022302e-16  5.55111512e-17  0.00000000e+00]
